[book]
authors = ["dimkar"]
language = "en"
multilingual = false
src = "src"
title = "SEO - Security Engineer Odyssey"

[output.html]
default-theme = "latte"
preferred-dark-theme = "mocha"
additional-css = ["theme/catppuccin.css", "theme/custom.css"]
